localstack:
  image: localstack/localstack
  ports:
    - "4567-4583:4567-4583"
    - "8080:8080"
dynamodb:
  image: peopleperhour/dynamodb
  ports:
    - "45678:8000"
s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"