sns:
  image: "wellcome/fake-sns"
  ports:
    - "9292:9292"
s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - "http.host=0.0.0.0"
    - "transport.host=0.0.0.0"
    - "cluster.name=wellcome"
    - "ES_JAVA_OPTS=-Xms750m -Xmx750m"