sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
localstack:
  image: localstack/localstack
  ports:
    - "4567-4583:4567-4583"
    - "8080:8080"
dynamodb:
  image: peopleperhour/dynamodb
  ports:
    - "45678:8000"
