s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"
localstack:
  image: localstack/localstack
  ports:
    - "4567-4583:4567-4583"
wiremock:
  image: rodolpheche/wiremock
  ports:
    - "8080:8080"
  volumes:
    - "${ROOT}/sierra_adapter/sierra_reader/src/test/resources/wiremock:/home/wiremock"
