addSbtPlugin("io.spray" % "sbt-revolver" % "0.8.0")
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.20")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.1.4")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.8")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
