ROOT = $(shell git rev-parse --show-toplevel)
include $(ROOT)/makefiles/functions.Makefile

STACK_ROOT 	= builds

PYTHON_APPS     =
PYTHON_SSM_APPS =
LAMBDAS 	    = notify_pushes

$(val $(call stack_setup))
