# This file is autogenerated.  To change the API pins, run 'make new-api-pins'.
production_api       = "remus"
pinned_romulus_app   = ""
pinned_romulus_nginx = ""
pinned_remus_app     = "14282700ae157f0b47f8cbe71149024e803f0167"
pinned_remus_nginx   = "4d0b58c7cd5feefbe77637f7fcda0d93b645e11b"
